### ISSUE TITLE
Add all contributors to readme

### ISSUE THREAD

**Issue by outsider0x0** [Tsirimaholy/HelloWorld#2]

**Comment by outsider0x0** [comment]
@all-contributors bot add @outsider0x0 to doc

**Comment by outsider0x0** [comment]
@Tsirimaholy can be add to idea. 
cc @all-contributors.

**Comment by Tsirimaholy** [comment]
@Tsirimaholy can be add to idea.
cc @all-contributors

**Comment by Tsirimaholy** [comment]
@Tsirimaholy can be add to idea @all-contributors.

**Comment by Tsirimaholy** [comment]
@all-contributors add @Tsirimaholy for code

**Comment by Tsirimaholy** [comment]
@all-contributors add @Tsirimaholy for idea
